name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: sudo apt-get update -q
      - run: sudo apt-get install libglfw3-dev xorg-dev libgl1-mesa-dev -y --allow-unauthenticated
      - run: zig fmt --check src/*.zig
      - run: zig build

  build_osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: brew install glfw
      - run: ln -s "$(xcrun --sdk macosx --show-sdk-path)/System/Library/Frameworks/OpenGL.framework/Headers" /usr/local/include/OpenGL
      - run: zig fmt --check src/*.zig
      - run: ZIG_SYSTEM_LINKER_HACK=1 zig build
